spring.application.name=TurismoUQ
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=AGENTE
spring.datasource.password=Agente123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# No registrar como WARN las excepciones de negocio de Oracle (ORA-20100, 20101, 20102...)
logging.level.org.hibernate.orm.jdbc.error=ERROR